package errors

import "errors"

var (
	//ErrorInformationNotExpected ...
	ErrorInformationNotExpected = errors.New("The expected information is not being provided")

	//ErrorInformationNotProvided ...
	ErrorInformationNotProvided = errors.New("The required information is not being provided")

	//ErrorConsultingData ...
	ErrorConsultingData = errors.New("An error has occurred consulting the data")

	//ErrorReadingData ...
	ErrorReadingData = errors.New("An error has occurred reading the data")

	//ErrorWritingData ...
	ErrorWritingData = errors.New("An error has occurred writing the data")

	//ErrorPathNotExist ...
	ErrorPathNotExist = errors.New("Path does not exist")

	//ErrorCheckExistence ...
	ErrorCheckExistence = errors.New("An error has occurred verifying the existence of the file/directory")

	//ErrorDecompressingFile ...
	ErrorDecompressingFile = errors.New("An error has occurred decompressing file")

	//ErrorFileCorrupted ...
	ErrorFileCorrupted = errors.New("The file is corrupted")

	//ErrorCreatingFileDirectory ...
	ErrorCreatingFileDirectory = errors.New("An error occurred creating the file/directory")

	//ErrorConnection ...
	ErrorConnection = errors.New("Error making the connection")

	//ErrorIncorrectCredentials ...
	ErrorIncorrectCredentials = errors.New("Incorrect username or password")

	//ErrorFTPGetFile ...
	ErrorFTPGetFile = errors.New("An error has occurred obtaining file from the FTP server")

	//ErrorFTPRecordingData ...
	ErrorFTPRecordingData = errors.New("An error has occurred recording the data of the remote file in the local file")

	//ErrorNewRequest ...
	ErrorNewRequest = errors.New("An error has occurred creating a new request")

	//ErrorMakingRequest ...
	ErrorMakingRequest = errors.New("An error has occurred making the request")

	//ErrorTokenInvalid ...
	ErrorTokenInvalid = errors.New("The access token provided is invalid")

	//ErrorTokenRequired ...
	ErrorTokenRequired = errors.New("An access token is required to continue")

	//ErrorConnectingDatabase ...
	ErrorConnectingDatabase = errors.New("An error has occurred connecting to the database")

	//ErrorDeleteDatabase ...
	ErrorDeleteDatabase = errors.New("An error occurred removing the database")

	//ErrorGetAllDocument ...
	ErrorGetAllDocument = errors.New("An error has occurred obtaining all the documents")

	//ErrorGetDocument ...
	ErrorGetDocument = errors.New("An error has occurred obtaining the document")

	//ErrorSearchDocument ...
	ErrorSearchDocument = errors.New("An error has occurred looking for a document")

	//ErrorCreateDocument ...
	ErrorCreateDocument = errors.New("An error has occurred creating a document")

	//ErrorUpdateDocument ...
	ErrorUpdateDocument = errors.New("An error has occurred updating a document")

	//ErrorCategoryNotGrouped ...
	ErrorCategoryNotGrouped = errors.New("Category not grouped")

	//ErrorAnonymousNotHaveProfile ...
	ErrorAnonymousNotHaveProfile = errors.New("The anonymous user does not have a profile")

	//ErrorUserNotFoundInContext ...
	ErrorUserNotFoundInContext = errors.New("The user was not found in the context")

	//ErrorRequestWithoutAuthorization ...
	ErrorRequestWithoutAuthorization = errors.New("You do not have permissions to make requests to this resource")
)
